# Generated by Django 3.2.3 on 2023-03-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.IntegerField(verbose_name=False)),
                ('jwelery', models.CharField(max_length=100)),
                ('design', models.ImageField(blank=True, null=True, upload_to='sample_design', verbose_name='jwelery design Image')),
                ('subject', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
    ]
