# Generated by Django 3.2.3 on 2023-03-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='design',
            field=models.ImageField(default='', upload_to='sample_design/img'),
        ),
    ]
