# Generated by Django 3.2.3 on 2023-04-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_contactus_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('otp', models.IntegerField(default=0)),
            ],
        ),
    ]
