# Generated by Django 3.2.3 on 2023-04-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20230405_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='design',
            field=models.ImageField(blank=True, null=True, upload_to='product/custom_design', verbose_name='Custom design'),
        ),
    ]
